apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Використовуємо назву сервісу. 
  # Клієнт підключиться до одного, а потім дізнається адреси всіх інших через нього.
  HAZELCAST_MEMBERS: "hazelcast-service:5701"
  
  # Маршрути для сервісів
  LOGGING_SERVICE_URL: "http://logging-service:8000"
  COUNTER_SERVICE_URL: "http://counter-service:8000"
  
  # Налаштування бази даних (для counter-service)
  POSTGRES_DB: "microservices_db"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/microservices_db"