apiVersion: v1
kind: Service
metadata:
  name: facade-service
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30001
  selector:
    app: facade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade
  template:
    metadata:
      labels:
        app: facade
    spec:
      containers:
      - name: facade
        image: microservices-facade:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: app-config